### PR TITLE
MP-3298: support running in offline mode.

### PR DESCRIPTION
**Pull request by serejke**
Added `-offline` CLI property that allows to run Plugin Verifier without internet

### CODE REVIEW

**Comment by serejke** [comment]
@gharrma all necessary plugin's dependencies must be downloaded to [`<plugins-directory>`](https://github.com/JetBrains/intellij-plugin-verifier/#technical-details) beforehand. Missing plugins will be reported accordingly.

**Comment by gharrma** [comment]
Thank you, Sergey!
I tested this in our build and it works perfectly.

**Review by gharrma — APPROVED** [review]

**Comment by serejke** [comment]
Published [v1.253](https://github.com/JetBrains/intellij-plugin-verifier/releases/tag/v1.253)

**Comment by lmy668** [comment]
> @gharrma all necessary plugin's dependencies must be downloaded to [`<plugins-directory>`](https://github.com/JetBrains/intellij-plugin-verifier/#technical-details) beforehand. Missing plugins will be reported accordingly.

hi, i want to set runPluginVerifier in task at offline, can you provide a demo configruation about build.gradle.kts? Thanks.

**Comment by gharrma** [comment]
> hi, i want to set runPluginVerifier in task at offline, can you provide a demo configruation about build.gradle.kts? Thanks.

We used the `-offline` flag in Bazel, not Gradle. So I don't have a `build.gradle.kts` example on hand. Sorry!

**Pull request merged**
